<div class="container">
    <!-- Title Section -->
    <div class ="title-bonus" style="padding:28px 0 0 0;position: relative !important;margin-bottom: 0px !important">
        <div style="padding:0 15px;background:white;width: 200px;margin-left: 41%;">
            <h1 style="margin-bottom: 25px !important;text-align:center;font-weight:900 !important;font-size:21px;color:#444;font-family: 'Montserrat', sans-serif;">
                <?= __('Special Request')?>
            </h1>
        </div>
    </div>

    <!-- Description Section -->
    <div class="hide-section" style="text-align: center; max-width: 900px; margin: 0 auto 50px; color: #111111; font-weight: 400; font-family: 'Montserrat', sans-serif; font-size: 13px;">
        <?= $block->getAdminBlockHtml('special-request-descreption'); ?>
    </div>

    <!-- Content Row -->
    <div class="row mb-4">
        <div class="col-12 col-md-6 mb-3 mb-md-0 hide-section" style="padding-right: 25px !important;">
            <?= $block->getAdminBlockHtml('special-request-image'); ?>
        </div>
        <div class="col-12 col-md-6 form-container" style="background-color: #f7f7f7; padding: 30px;">
            <form class ="special-request-container" action="<?= $block->getUrl('specialrequest/form/submit') ?>" method="post" enctype="multipart/form-data">
                <label style="font-size:13px;color:#111111" for="full_name"><?= __('Full Name') ?></label>
                <input type="text" name="full_name" required style="height: 48px;background: #FFFFFF;border: 1px solid #EEEEEE;border-radius: 6px;font-size: 14px;margin-bottom:10px"><br>

                <label style="font-size:13px;color:#111111" for="entity_name"><?= __('Entity name') ?></label>
                <input type="text" name="entity_name" required style="height: 48px;background: #FFFFFF;border: 1px solid #EEEEEE;border-radius: 6px;font-size: 14px;margin-bottom:10px"><br>

                <label style="font-size:13px;color:#111111" for="email"><?= __('Email') ?></label>
                <input type="email" name="email" required style="height: 48px;background: #FFFFFF;border: 1px solid #EEEEEE;border-radius: 6px;font-size: 14px;margin-bottom:10px"><br>    

                <label style="font-size:13px;color:#111111" for="phone"><?= __('Phone') ?></label>
                <input type="text" name="phone" required style="height: 48px;background: #FFFFFF;border: 1px solid #EEEEEE;border-radius: 6px;font-size: 14px;margin-bottom:10px"><br>

                <label style="font-size:13px;color:#111111" for="special_req"><?= __('Special Request') ?></label>
                <textarea id="special_req" name="special_req" rows="4" required style="background: #FFFFFF;border: 1px solid #EEEEEE;border-radius: 6px;font-size: 14px;margin-bottom:10px"></textarea><br>

                <label style="font-size:13px;color:#111111" for="file_to_upload"><?= __('Attach your file (photo, excel, word or pdf)') ?></label><br>
                <input type="file" name="upload_file" required><br>

                <button style="background: #222; font-size: 15px; padding: 15px 0px; font-weight: 900; margin-top: 23px; width: 100%; border: 0; border-radius: 0;" type="submit">
                    <?= __('Submit')?>
                </button>
            </form>
        </div>
    </div>
</div>
